#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define PRODUCER_NONE                          0
#define PRODUCER_SAWYER_1                      1
#define PRODUCER_GRUNT_AQUA_HIDEOUT_1          2
#define PRODUCER_GRUNT_AQUA_HIDEOUT_2          3
#define PRODUCER_GRUNT_AQUA_HIDEOUT_3          4
#define PRODUCER_GRUNT_AQUA_HIDEOUT_4          5
#define PRODUCER_GRUNT_SEAFLOOR_CAVERN_1       6
#define PRODUCER_GRUNT_SEAFLOOR_CAVERN_2       7
#define PRODUCER_GRUNT_SEAFLOOR_CAVERN_3       8
#define PRODUCER_GABRIELLE_1                   9
#define PRODUCER_GRUNT_PETALBURG_WOODS        10
#define PRODUCER_MARCEL                       11
#define PRODUCER_ALBERTO                      12
#define PRODUCER_ED                           13
#define PRODUCER_GRUNT_SEAFLOOR_CAVERN_4      14
#define PRODUCER_DECLAN                       15
#define PRODUCER_GRUNT_RUSTURF_TUNNEL         16
#define PRODUCER_GRUNT_WEATHER_INST_1         17
#define PRODUCER_GRUNT_WEATHER_INST_2         18
#define PRODUCER_GRUNT_WEATHER_INST_3         19
#define PRODUCER_GRUNT_MUSEUM_1               20
#define PRODUCER_GRUNT_MUSEUM_2               21
#define PRODUCER_GRUNT_SPACE_CENTER_1         22
#define PRODUCER_GRUNT_MT_PYRE_1              23
#define PRODUCER_GRUNT_MT_PYRE_2              24
#define PRODUCER_GRUNT_MT_PYRE_3              25
#define PRODUCER_GRUNT_WEATHER_INST_4         26
#define PRODUCER_GRUNT_AQUA_HIDEOUT_5         27
#define PRODUCER_GRUNT_AQUA_HIDEOUT_6         28
#define PRODUCER_FREDRICK                     29
#define PRODUCER_MATT                         30
#define PRODUCER_ZANDER                       31
#define PRODUCER_SHELLY_WEATHER_INSTITUTE     32
#define PRODUCER_SHELLY_SEAFLOOR_CAVERN       33
#define PRODUCER_ARCHIE                       34
#define PRODUCER_LEAH                         35
#define PRODUCER_DAISY                        36
#define PRODUCER_ROSE_1                       37
#define PRODUCER_FELIX                        38
#define PRODUCER_VIOLET                       39
#define PRODUCER_ROSE_2                       40
#define PRODUCER_ROSE_3                       41
#define PRODUCER_ROSE_4                       42
#define PRODUCER_ROSE_5                       43
#define PRODUCER_DUSTY_1                      44
#define PRODUCER_CHIP                         45
#define PRODUCER_FOSTER                       46
#define PRODUCER_DUSTY_2                      47
#define PRODUCER_DUSTY_3                      48
#define PRODUCER_DUSTY_4                      49
#define PRODUCER_DUSTY_5                      50
#define PRODUCER_GABBY_AND_TY_1               51
#define PRODUCER_GABBY_AND_TY_2               52
#define PRODUCER_GABBY_AND_TY_3               53
#define PRODUCER_GABBY_AND_TY_4               54
#define PRODUCER_GABBY_AND_TY_5               55
#define PRODUCER_GABBY_AND_TY_6               56
#define PRODUCER_LOLA_1                       57
#define PRODUCER_AUSTINA                      58
#define PRODUCER_GWEN                         59
#define PRODUCER_LOLA_2                       60
#define PRODUCER_LOLA_3                       61
#define PRODUCER_LOLA_4                       62
#define PRODUCER_LOLA_5                       63
#define PRODUCER_RICKY_1                      64
#define PRODUCER_SIMON                        65
#define PRODUCER_CHARLIE                      66
#define PRODUCER_RICKY_2                      67
#define PRODUCER_RICKY_3                      68
#define PRODUCER_RICKY_4                      69
#define PRODUCER_RICKY_5                      70
#define PRODUCER_RANDALL                      71
#define PRODUCER_PARKER                       72
#define PRODUCER_GEORGE                       73
#define PRODUCER_BERKE                        74
#define PRODUCER_BRAXTON                      75
#define PRODUCER_VINCENT                      76
#define PRODUCER_LEROY                        77
#define PRODUCER_WILTON_1                     78
#define PRODUCER_EDGAR                        79
#define PRODUCER_ALBERT                       80
#define PRODUCER_SAMUEL                       81
#define PRODUCER_VITO                         82
#define PRODUCER_OWEN                         83
#define PRODUCER_WILTON_2                     84
#define PRODUCER_WILTON_3                     85
#define PRODUCER_WILTON_4                     86
#define PRODUCER_WILTON_5                     87
#define PRODUCER_WARREN                       88
#define PRODUCER_MARY                         89
#define PRODUCER_ALEXIA                       90
#define PRODUCER_JODY                         91
#define PRODUCER_WENDY                        92
#define PRODUCER_KEIRA                        93
#define PRODUCER_BROOKE_1                     94
#define PRODUCER_JENNIFER                     95
#define PRODUCER_HOPE                         96
#define PRODUCER_SHANNON                      97
#define PRODUCER_MICHELLE                     98
#define PRODUCER_CAROLINE                     99
#define PRODUCER_JULIE                       100
#define PRODUCER_BROOKE_2                    101
#define PRODUCER_BROOKE_3                    102
#define PRODUCER_BROOKE_4                    103
#define PRODUCER_BROOKE_5                    104
#define PRODUCER_PATRICIA                    105
#define PRODUCER_KINDRA                      106
#define PRODUCER_TAMMY                       107
#define PRODUCER_VALERIE_1                   108
#define PRODUCER_TASHA                       109
#define PRODUCER_VALERIE_2                   110
#define PRODUCER_VALERIE_3                   111
#define PRODUCER_VALERIE_4                   112
#define PRODUCER_VALERIE_5                   113
#define PRODUCER_CINDY_1                     114
#define PRODUCER_DAPHNE                      115
#define PRODUCER_GRUNT_SPACE_CENTER_2        116
#define PRODUCER_CINDY_2                     117
#define PRODUCER_BRIANNA                     118
#define PRODUCER_NAOMI                       119
#define PRODUCER_CINDY_3                     120
#define PRODUCER_CINDY_4                     121
#define PRODUCER_CINDY_5                     122
#define PRODUCER_CINDY_6                     123
#define PRODUCER_MELISSA                     124
#define PRODUCER_SHEILA                      125
#define PRODUCER_SHIRLEY                     126
#define PRODUCER_JESSICA_1                   127
#define PRODUCER_CONNIE                      128
#define PRODUCER_BRIDGET                     129
#define PRODUCER_OLIVIA                      130
#define PRODUCER_TIFFANY                     131
#define PRODUCER_JESSICA_2                   132
#define PRODUCER_JESSICA_3                   133
#define PRODUCER_JESSICA_4                   134
#define PRODUCER_JESSICA_5                   135
#define PRODUCER_WINSTON_1                   136
#define PRODUCER_MOLLIE                      137
#define PRODUCER_GARRET                      138
#define PRODUCER_WINSTON_2                   139
#define PRODUCER_WINSTON_3                   140
#define PRODUCER_WINSTON_4                   141
#define PRODUCER_WINSTON_5                   142
#define PRODUCER_STEVE_1                     143
#define PRODUCER_THALIA_1                    144
#define PRODUCER_MARK                        145
#define PRODUCER_GRUNT_MT_CHIMNEY_1          146
#define PRODUCER_STEVE_2                     147
#define PRODUCER_STEVE_3                     148
#define PRODUCER_STEVE_4                     149
#define PRODUCER_STEVE_5                     150
#define PRODUCER_LUIS                        151
#define PRODUCER_DOMINIK                     152
#define PRODUCER_DOUGLAS                     153
#define PRODUCER_DARRIN                      154
#define PRODUCER_TONY_1                      155
#define PRODUCER_JEROME                      156
#define PRODUCER_MATTHEW                     157
#define PRODUCER_DAVID                       158
#define PRODUCER_SPENCER                     159
#define PRODUCER_ROLAND                      160
#define PRODUCER_NOLEN                       161
#define PRODUCER_STAN                        162
#define PRODUCER_BARRY                       163
#define PRODUCER_DEAN                        164
#define PRODUCER_RODNEY                      165
#define PRODUCER_RICHARD                     166
#define PRODUCER_HERMAN                      167
#define PRODUCER_SANTIAGO                    168
#define PRODUCER_GILBERT                     169
#define PRODUCER_FRANKLIN                    170
#define PRODUCER_KEVIN                       171
#define PRODUCER_JACK                        172
#define PRODUCER_DUDLEY                      173
#define PRODUCER_CHAD                        174
#define PRODUCER_TONY_2                      175
#define PRODUCER_TONY_3                      176
#define PRODUCER_TONY_4                      177
#define PRODUCER_TONY_5                      178
#define PRODUCER_TAKAO                       179
#define PRODUCER_HITOSHI                     180
#define PRODUCER_KIYO                        181
#define PRODUCER_KOICHI                      182
#define PRODUCER_NOB_1                       183
#define PRODUCER_NOB_2                       184
#define PRODUCER_NOB_3                       185
#define PRODUCER_NOB_4                       186
#define PRODUCER_NOB_5                       187
#define PRODUCER_YUJI                        188
#define PRODUCER_DAISUKE                     189
#define PRODUCER_ATSUSHI                     190
#define PRODUCER_KIRK                        191
#define PRODUCER_GRUNT_AQUA_HIDEOUT_7        192
#define PRODUCER_GRUNT_AQUA_HIDEOUT_8        193
#define PRODUCER_SHAWN                       194
#define PRODUCER_FERNANDO_1                  195
#define PRODUCER_DALTON_1                    196
#define PRODUCER_DALTON_2                    197
#define PRODUCER_DALTON_3                    198
#define PRODUCER_DALTON_4                    199
#define PRODUCER_DALTON_5                    200
#define PRODUCER_COLE                        201
#define PRODUCER_JEFF                        202
#define PRODUCER_AXLE                        203
#define PRODUCER_JACE                        204
#define PRODUCER_KEEGAN                      205
#define PRODUCER_BERNIE_1                    206
#define PRODUCER_BERNIE_2                    207
#define PRODUCER_BERNIE_3                    208
#define PRODUCER_BERNIE_4                    209
#define PRODUCER_BERNIE_5                    210
#define PRODUCER_DREW                        211
#define PRODUCER_BEAU                        212
#define PRODUCER_LARRY                       213
#define PRODUCER_SHANE                       214
#define PRODUCER_JUSTIN                      215
#define PRODUCER_ETHAN_1                     216
#define PRODUCER_AUTUMN                      217
#define PRODUCER_TRAVIS                      218
#define PRODUCER_ETHAN_2                     219
#define PRODUCER_ETHAN_3                     220
#define PRODUCER_ETHAN_4                     221
#define PRODUCER_ETHAN_5                     222
#define PRODUCER_BRENT                       223
#define PRODUCER_DONALD                      224
#define PRODUCER_TAYLOR                      225
#define PRODUCER_JEFFREY_1                   226
#define PRODUCER_DEREK                       227
#define PRODUCER_JEFFREY_2                   228
#define PRODUCER_JEFFREY_3                   229
#define PRODUCER_JEFFREY_4                   230
#define PRODUCER_JEFFREY_5                   231
#define PRODUCER_EDWARD                      232
#define PRODUCER_PRESTON                     233
#define PRODUCER_VIRGIL                      234
#define PRODUCER_BLAKE                       235
#define PRODUCER_WILLIAM                     236
#define PRODUCER_JOSHUA                      237
#define PRODUCER_CAMERON_1                   238
#define PRODUCER_CAMERON_2                   239
#define PRODUCER_CAMERON_3                   240
#define PRODUCER_CAMERON_4                   241
#define PRODUCER_CAMERON_5                   242
#define PRODUCER_JACLYN                      243
#define PRODUCER_HANNAH                      244
#define PRODUCER_SAMANTHA                    245
#define PRODUCER_MAURA                       246
#define PRODUCER_KAYLA                       247
#define PRODUCER_ALEXIS                      248
#define PRODUCER_JACKI_1                     249
#define PRODUCER_JACKI_2                     250
#define PRODUCER_JACKI_3                     251
#define PRODUCER_JACKI_4                     252
#define PRODUCER_JACKI_5                     253
#define PRODUCER_WALTER_1                    254
#define PRODUCER_MICAH                       255
#define PRODUCER_THOMAS                      256
#define PRODUCER_WALTER_2                    257
#define PRODUCER_WALTER_3                    258
#define PRODUCER_WALTER_4                    259
#define PRODUCER_WALTER_5                    260
#define PRODUCER_SIDNEY                      261
#define PRODUCER_PHOEBE                      262
#define PRODUCER_GLACIA                      263
#define PRODUCER_DRAKE                       264
#define PRODUCER_ROXANNE_1                   265
#define PRODUCER_BRAWLY_1                    266
#define PRODUCER_WATTSON_1                   267
#define PRODUCER_FLANNERY_1                  268
#define PRODUCER_NORMAN_1                    269
#define PRODUCER_WINONA_1                    270
#define PRODUCER_TATE_AND_LIZA_1             271
#define PRODUCER_JUAN_1                      272
#define PRODUCER_JERRY_1                     273
#define PRODUCER_TED                         274
#define PRODUCER_PAUL                        275
#define PRODUCER_JERRY_2                     276
#define PRODUCER_JERRY_3                     277
#define PRODUCER_JERRY_4                     278
#define PRODUCER_JERRY_5                     279
#define PRODUCER_KAREN_1                     280
#define PRODUCER_GEORGIA                     281
#define PRODUCER_KAREN_2                     282
#define PRODUCER_KAREN_3                     283
#define PRODUCER_KAREN_4                     284
#define PRODUCER_KAREN_5                     285
#define PRODUCER_KATE_AND_JOY                286
#define PRODUCER_ANNA_AND_MEG_1              287
#define PRODUCER_ANNA_AND_MEG_2              288
#define PRODUCER_ANNA_AND_MEG_3              289
#define PRODUCER_ANNA_AND_MEG_4              290
#define PRODUCER_ANNA_AND_MEG_5              291
#define PRODUCER_VICTOR                      292
#define PRODUCER_MIGUEL_1                    293
#define PRODUCER_COLTON                      294
#define PRODUCER_MIGUEL_2                    295
#define PRODUCER_MIGUEL_3                    296
#define PRODUCER_MIGUEL_4                    297
#define PRODUCER_MIGUEL_5                    298
#define PRODUCER_VICTORIA                    299
#define PRODUCER_VANESSA                     300
#define PRODUCER_BETHANY                     301
#define PRODUCER_ISABEL_1                    302
#define PRODUCER_ISABEL_2                    303
#define PRODUCER_ISABEL_3                    304
#define PRODUCER_ISABEL_4                    305
#define PRODUCER_ISABEL_5                    306
#define PRODUCER_TIMOTHY_1                   307
#define PRODUCER_TIMOTHY_2                   308
#define PRODUCER_TIMOTHY_3                   309
#define PRODUCER_TIMOTHY_4                   310
#define PRODUCER_TIMOTHY_5                   311
#define PRODUCER_VICKY                       312
#define PRODUCER_SHELBY_1                    313
#define PRODUCER_SHELBY_2                    314
#define PRODUCER_SHELBY_3                    315
#define PRODUCER_SHELBY_4                    316
#define PRODUCER_SHELBY_5                    317
#define PRODUCER_CALVIN_1                    318
#define PRODUCER_BILLY                       319
#define PRODUCER_JOSH                        320
#define PRODUCER_TOMMY                       321
#define PRODUCER_JOEY                        322
#define PRODUCER_BEN                         323
#define PRODUCER_QUINCY                      324
#define PRODUCER_KATELYNN                    325
#define PRODUCER_JAYLEN                      326
#define PRODUCER_DILLON                      327
#define PRODUCER_CALVIN_2                    328
#define PRODUCER_CALVIN_3                    329
#define PRODUCER_CALVIN_4                    330
#define PRODUCER_CALVIN_5                    331
#define PRODUCER_EDDIE                       332
#define PRODUCER_ALLEN                       333
#define PRODUCER_TIMMY                       334
#define PRODUCER_WALLACE                     335
#define PRODUCER_ANDREW                      336
#define PRODUCER_IVAN                        337
#define PRODUCER_CLAUDE                      338
#define PRODUCER_ELLIOT_1                    339
#define PRODUCER_NED                         340
#define PRODUCER_DALE                        341
#define PRODUCER_NOLAN                       342
#define PRODUCER_BARNY                       343
#define PRODUCER_WADE                        344
#define PRODUCER_CARTER                      345
#define PRODUCER_ELLIOT_2                    346
#define PRODUCER_ELLIOT_3                    347
#define PRODUCER_ELLIOT_4                    348
#define PRODUCER_ELLIOT_5                    349
#define PRODUCER_RONALD                      350
#define PRODUCER_JACOB                       351
#define PRODUCER_ANTHONY                     352
#define PRODUCER_BENJAMIN_1                  353
#define PRODUCER_BENJAMIN_2                  354
#define PRODUCER_BENJAMIN_3                  355
#define PRODUCER_BENJAMIN_4                  356
#define PRODUCER_BENJAMIN_5                  357
#define PRODUCER_ABIGAIL_1                   358
#define PRODUCER_JASMINE                     359
#define PRODUCER_ABIGAIL_2                   360
#define PRODUCER_ABIGAIL_3                   361
#define PRODUCER_ABIGAIL_4                   362
#define PRODUCER_ABIGAIL_5                   363
#define PRODUCER_DYLAN_1                     364
#define PRODUCER_DYLAN_2                     365
#define PRODUCER_DYLAN_3                     366
#define PRODUCER_DYLAN_4                     367
#define PRODUCER_DYLAN_5                     368
#define PRODUCER_MARIA_1                     369
#define PRODUCER_MARIA_2                     370
#define PRODUCER_MARIA_3                     371
#define PRODUCER_MARIA_4                     372
#define PRODUCER_MARIA_5                     373
#define PRODUCER_CAMDEN                      374
#define PRODUCER_DEMETRIUS                   375
#define PRODUCER_ISAIAH_1                    376
#define PRODUCER_PABLO_1                     377
#define PRODUCER_CHASE                       378
#define PRODUCER_ISAIAH_2                    379
#define PRODUCER_ISAIAH_3                    380
#define PRODUCER_ISAIAH_4                    381
#define PRODUCER_ISAIAH_5                    382
#define PRODUCER_ISOBEL                      383
#define PRODUCER_DONNY                       384
#define PRODUCER_TALIA                       385
#define PRODUCER_KATELYN_1                   386
#define PRODUCER_ALLISON                     387
#define PRODUCER_KATELYN_2                   388
#define PRODUCER_KATELYN_3                   389
#define PRODUCER_KATELYN_4                   390
#define PRODUCER_KATELYN_5                   391
#define PRODUCER_NICOLAS_1                   392
#define PRODUCER_NICOLAS_2                   393
#define PRODUCER_NICOLAS_3                   394
#define PRODUCER_NICOLAS_4                   395
#define PRODUCER_NICOLAS_5                   396
#define PRODUCER_AARON                       397
#define PRODUCER_PERRY                       398
#define PRODUCER_HUGH                        399
#define PRODUCER_PHIL                        400
#define PRODUCER_JARED                       401
#define PRODUCER_HUMBERTO                    402
#define PRODUCER_PRESLEY                     403
#define PRODUCER_EDWARDO                     404
#define PRODUCER_COLIN                       405
#define PRODUCER_ROBERT_1                    406
#define PRODUCER_BENNY                       407
#define PRODUCER_CHESTER                     408
#define PRODUCER_ROBERT_2                    409
#define PRODUCER_ROBERT_3                    410
#define PRODUCER_ROBERT_4                    411
#define PRODUCER_ROBERT_5                    412
#define PRODUCER_ALEX                        413
#define PRODUCER_BECK                        414
#define PRODUCER_YASU                        415
#define PRODUCER_TAKASHI                     416
#define PRODUCER_DIANNE                      417
#define PRODUCER_JANI                        418
#define PRODUCER_LAO_1                       419
#define PRODUCER_LUNG                        420
#define PRODUCER_LAO_2                       421
#define PRODUCER_LAO_3                       422
#define PRODUCER_LAO_4                       423
#define PRODUCER_LAO_5                       424
#define PRODUCER_JOCELYN                     425
#define PRODUCER_LAURA                       426
#define PRODUCER_CYNDY_1                     427
#define PRODUCER_CORA                        428
#define PRODUCER_PAULA                       429
#define PRODUCER_CYNDY_2                     430
#define PRODUCER_CYNDY_3                     431
#define PRODUCER_CYNDY_4                     432
#define PRODUCER_CYNDY_5                     433
#define PRODUCER_MADELINE_1                  434
#define PRODUCER_CLARISSA                    435
#define PRODUCER_ANGELICA                    436
#define PRODUCER_MADELINE_2                  437
#define PRODUCER_MADELINE_3                  438
#define PRODUCER_MADELINE_4                  439
#define PRODUCER_MADELINE_5                  440
#define PRODUCER_BEVERLY                     441
#define PRODUCER_IMANI                       442
#define PRODUCER_KYLA                        443
#define PRODUCER_DENISE                      444
#define PRODUCER_BETH                        445
#define PRODUCER_TARA                        446
#define PRODUCER_MISSY                       447
#define PRODUCER_ALICE                       448
#define PRODUCER_JENNY_1                     449
#define PRODUCER_GRACE                       450
#define PRODUCER_TANYA                       451
#define PRODUCER_SHARON                      452
#define PRODUCER_NIKKI                       453
#define PRODUCER_BRENDA                      454
#define PRODUCER_KATIE                       455
#define PRODUCER_SUSIE                       456
#define PRODUCER_KARA                        457
#define PRODUCER_DANA                        458
#define PRODUCER_SIENNA                      459
#define PRODUCER_DEBRA                       460
#define PRODUCER_LINDA                       461
#define PRODUCER_KAYLEE                      462
#define PRODUCER_LAUREL                      463
#define PRODUCER_CARLEE                      464
#define PRODUCER_JENNY_2                     465
#define PRODUCER_JENNY_3                     466
#define PRODUCER_JENNY_4                     467
#define PRODUCER_JENNY_5                     468
#define PRODUCER_HEIDI                       469
#define PRODUCER_BECKY                       470
#define PRODUCER_CAROL                       471
#define PRODUCER_NANCY                       472
#define PRODUCER_MARTHA                      473
#define PRODUCER_DIANA_1                     474
#define PRODUCER_CEDRIC                      475
#define PRODUCER_IRENE                       476
#define PRODUCER_DIANA_2                     477
#define PRODUCER_DIANA_3                     478
#define PRODUCER_DIANA_4                     479
#define PRODUCER_DIANA_5                     480
#define PRODUCER_AMY_AND_LIV_1               481
#define PRODUCER_AMY_AND_LIV_2               482
#define PRODUCER_GINA_AND_MIA_1              483
#define PRODUCER_MIU_AND_YUKI                484
#define PRODUCER_AMY_AND_LIV_3               485
#define PRODUCER_GINA_AND_MIA_2              486
#define PRODUCER_AMY_AND_LIV_4               487
#define PRODUCER_AMY_AND_LIV_5               488
#define PRODUCER_AMY_AND_LIV_6               489
#define PRODUCER_HUEY                        490
#define PRODUCER_EDMOND                      491
#define PRODUCER_ERNEST_1                    492
#define PRODUCER_DWAYNE                      493
#define PRODUCER_PHILLIP                     494
#define PRODUCER_LEONARD                     495
#define PRODUCER_DUNCAN                      496
#define PRODUCER_ERNEST_2                    497
#define PRODUCER_ERNEST_3                    498
#define PRODUCER_ERNEST_4                    499
#define PRODUCER_ERNEST_5                    500
#define PRODUCER_ELI                         501
#define PRODUCER_ANNIKA                      502
#define PRODUCER_JAZMYN                      503
#define PRODUCER_JONAS                       504
#define PRODUCER_KAYLEY                      505
#define PRODUCER_AURON                       506
#define PRODUCER_KELVIN                      507
#define PRODUCER_MARLEY                      508
#define PRODUCER_REYNA                       509
#define PRODUCER_HUDSON                      510
#define PRODUCER_CONOR                       511
#define PRODUCER_EDWIN_1                     512
#define PRODUCER_HECTOR                      513
#define PRODUCER_TABITHA_MOSSDEEP            514
#define PRODUCER_EDWIN_2                     515
#define PRODUCER_EDWIN_3                     516
#define PRODUCER_EDWIN_4                     517
#define PRODUCER_EDWIN_5                     518
#define PRODUCER_WALLY_VR_1                  519
#define PRODUCER_BRENDAN_ROUTE_103_MUDKIP    520
#define PRODUCER_BRENDAN_ROUTE_110_MUDKIP    521
#define PRODUCER_BRENDAN_ROUTE_119_MUDKIP    522
#define PRODUCER_BRENDAN_ROUTE_103_TREECKO   523
#define PRODUCER_BRENDAN_ROUTE_110_TREECKO   524
#define PRODUCER_BRENDAN_ROUTE_119_TREECKO   525
#define PRODUCER_BRENDAN_ROUTE_103_TORCHIC   526
#define PRODUCER_BRENDAN_ROUTE_110_TORCHIC   527
#define PRODUCER_BRENDAN_ROUTE_119_TORCHIC   528
#define PRODUCER_MAY_ROUTE_103_MUDKIP        529
#define PRODUCER_MAY_ROUTE_110_MUDKIP        530
#define PRODUCER_MAY_ROUTE_119_MUDKIP        531
#define PRODUCER_MAY_ROUTE_103_TREECKO       532
#define PRODUCER_MAY_ROUTE_110_TREECKO       533
#define PRODUCER_MAY_ROUTE_119_TREECKO       534
#define PRODUCER_MAY_ROUTE_103_TORCHIC       535
#define PRODUCER_MAY_ROUTE_110_TORCHIC       536
#define PRODUCER_MAY_ROUTE_119_TORCHIC       537
#define PRODUCER_ISAAC_1                     538
#define PRODUCER_DAVIS                       539
#define PRODUCER_MITCHELL                    540
#define PRODUCER_ISAAC_2                     541
#define PRODUCER_ISAAC_3                     542
#define PRODUCER_ISAAC_4                     543
#define PRODUCER_ISAAC_5                     544
#define PRODUCER_LYDIA_1                     545
#define PRODUCER_HALLE                       546
#define PRODUCER_GARRISON                    547
#define PRODUCER_LYDIA_2                     548
#define PRODUCER_LYDIA_3                     549
#define PRODUCER_LYDIA_4                     550
#define PRODUCER_LYDIA_5                     551
#define PRODUCER_JACKSON_1                   552
#define PRODUCER_LORENZO                     553
#define PRODUCER_SEBASTIAN                   554
#define PRODUCER_JACKSON_2                   555
#define PRODUCER_JACKSON_3                   556
#define PRODUCER_JACKSON_4                   557
#define PRODUCER_JACKSON_5                   558
#define PRODUCER_CATHERINE_1                 559
#define PRODUCER_JENNA                       560
#define PRODUCER_SOPHIA                      561
#define PRODUCER_CATHERINE_2                 562
#define PRODUCER_CATHERINE_3                 563
#define PRODUCER_CATHERINE_4                 564
#define PRODUCER_CATHERINE_5                 565
#define PRODUCER_JULIO                       566
#define PRODUCER_GRUNT_SEAFLOOR_CAVERN_5     567
#define PRODUCER_GRUNT_UNUSED                568
#define PRODUCER_GRUNT_MT_PYRE_4             569
#define PRODUCER_GRUNT_JAGGED_PASS           570
#define PRODUCER_MARC                        571
#define PRODUCER_BRENDEN                     572
#define PRODUCER_LILITH                      573
#define PRODUCER_CRISTIAN                    574
#define PRODUCER_SYLVIA                      575
#define PRODUCER_LEONARDO                    576
#define PRODUCER_ATHENA                      577
#define PRODUCER_HARRISON                    578
#define PRODUCER_GRUNT_MT_CHIMNEY_2          579
#define PRODUCER_CLARENCE                    580
#define PRODUCER_TERRY                       581
#define PRODUCER_NATE                        582
#define PRODUCER_KATHLEEN                    583
#define PRODUCER_CLIFFORD                    584
#define PRODUCER_NICHOLAS                    585
#define PRODUCER_GRUNT_SPACE_CENTER_3        586
#define PRODUCER_GRUNT_SPACE_CENTER_4        587
#define PRODUCER_GRUNT_SPACE_CENTER_5        588
#define PRODUCER_GRUNT_SPACE_CENTER_6        589
#define PRODUCER_GRUNT_SPACE_CENTER_7        590
#define PRODUCER_MACEY                       591
#define PRODUCER_BRENDAN_RUSTBORO_TREECKO    592
#define PRODUCER_BRENDAN_RUSTBORO_MUDKIP     593
#define PRODUCER_PAXTON                      594
#define PRODUCER_ISABELLA                    595
#define PRODUCER_GRUNT_WEATHER_INST_5        596
#define PRODUCER_TABITHA_MT_CHIMNEY          597
#define PRODUCER_JONATHAN                    598
#define PRODUCER_BRENDAN_RUSTBORO_TORCHIC    599
#define PRODUCER_MAY_RUSTBORO_MUDKIP         600
#define PRODUCER_MAXIE_MAGMA_HIDEOUT         601
#define PRODUCER_MAXIE_MT_CHIMNEY            602
#define PRODUCER_TIANA                       603
#define PRODUCER_HALEY_1                     604
#define PRODUCER_JANICE                      605
#define PRODUCER_VIVI                        606
#define PRODUCER_HALEY_2                     607
#define PRODUCER_HALEY_3                     608
#define PRODUCER_HALEY_4                     609
#define PRODUCER_HALEY_5                     610
#define PRODUCER_SALLY                       611
#define PRODUCER_ROBIN                       612
#define PRODUCER_ANDREA                      613
#define PRODUCER_CRISSY                      614
#define PRODUCER_RICK                        615
#define PRODUCER_LYLE                        616
#define PRODUCER_JOSE                        617
#define PRODUCER_DOUG                        618
#define PRODUCER_GREG                        619
#define PRODUCER_KENT                        620
#define PRODUCER_JAMES_1                     621
#define PRODUCER_JAMES_2                     622
#define PRODUCER_JAMES_3                     623
#define PRODUCER_JAMES_4                     624
#define PRODUCER_JAMES_5                     625
#define PRODUCER_BRICE                       626
#define PRODUCER_TRENT_1                     627
#define PRODUCER_LENNY                       628
#define PRODUCER_LUCAS_1                     629
#define PRODUCER_ALAN                        630
#define PRODUCER_CLARK                       631
#define PRODUCER_ERIC                        632
#define PRODUCER_LUCAS_2                     633
#define PRODUCER_MIKE_1                      634
#define PRODUCER_MIKE_2                      635
#define PRODUCER_TRENT_2                     636
#define PRODUCER_TRENT_3                     637
#define PRODUCER_TRENT_4                     638
#define PRODUCER_TRENT_5                     639
#define PRODUCER_DEZ_AND_LUKE                640
#define PRODUCER_LEA_AND_JED                 641
#define PRODUCER_KIRA_AND_DAN_1              642
#define PRODUCER_KIRA_AND_DAN_2              643
#define PRODUCER_KIRA_AND_DAN_3              644
#define PRODUCER_KIRA_AND_DAN_4              645
#define PRODUCER_KIRA_AND_DAN_5              646
#define PRODUCER_JOHANNA                     647
#define PRODUCER_GERALD                      648
#define PRODUCER_VIVIAN                      649
#define PRODUCER_DANIELLE                    650
#define PRODUCER_HIDEO                       651
#define PRODUCER_KEIGO                       652
#define PRODUCER_RILEY                       653
#define PRODUCER_FLINT                       654
#define PRODUCER_ASHLEY                      655
#define PRODUCER_WALLY_MAUVILLE              656
#define PRODUCER_WALLY_VR_2                  657
#define PRODUCER_WALLY_VR_3                  658
#define PRODUCER_WALLY_VR_4                  659
#define PRODUCER_WALLY_VR_5                  660
#define PRODUCER_BRENDAN_LILYCOVE_MUDKIP     661
#define PRODUCER_BRENDAN_LILYCOVE_TREECKO    662
#define PRODUCER_BRENDAN_LILYCOVE_TORCHIC    663
#define PRODUCER_MAY_LILYCOVE_MUDKIP         664
#define PRODUCER_MAY_LILYCOVE_TREECKO        665
#define PRODUCER_MAY_LILYCOVE_TORCHIC        666
#define PRODUCER_JONAH                       667
#define PRODUCER_HENRY                       668
#define PRODUCER_ROGER                       669
#define PRODUCER_ALEXA                       670
#define PRODUCER_RUBEN                       671
#define PRODUCER_KOJI_1                      672
#define PRODUCER_WAYNE                       673
#define PRODUCER_AIDAN                       674
#define PRODUCER_REED                        675
#define PRODUCER_TISHA                       676
#define PRODUCER_TORI_AND_TIA                677
#define PRODUCER_KIM_AND_IRIS                678
#define PRODUCER_TYRA_AND_IVY                679
#define PRODUCER_MEL_AND_PAUL                680
#define PRODUCER_JOHN_AND_JAY_1              681
#define PRODUCER_JOHN_AND_JAY_2              682
#define PRODUCER_JOHN_AND_JAY_3              683
#define PRODUCER_JOHN_AND_JAY_4              684
#define PRODUCER_JOHN_AND_JAY_5              685
#define PRODUCER_RELI_AND_IAN                686
#define PRODUCER_LILA_AND_ROY_1              687
#define PRODUCER_LILA_AND_ROY_2              688
#define PRODUCER_LILA_AND_ROY_3              689
#define PRODUCER_LILA_AND_ROY_4              690
#define PRODUCER_LILA_AND_ROY_5              691
#define PRODUCER_LISA_AND_RAY                692
#define PRODUCER_CHRIS                       693
#define PRODUCER_DAWSON                      694
#define PRODUCER_SARAH                       695
#define PRODUCER_DARIAN                      696
#define PRODUCER_HAILEY                      697
#define PRODUCER_CHANDLER                    698
#define PRODUCER_KALEB                       699
#define PRODUCER_JOSEPH                      700
#define PRODUCER_ALYSSA                      701
#define PRODUCER_MARCOS                      702
#define PRODUCER_RHETT                       703
#define PRODUCER_TYRON                       704
#define PRODUCER_CELINA                      705
#define PRODUCER_BIANCA                      706
#define PRODUCER_HAYDEN                      707
#define PRODUCER_SOPHIE                      708
#define PRODUCER_COBY                        709
#define PRODUCER_LAWRENCE                    710
#define PRODUCER_WYATT                       711
#define PRODUCER_ANGELINA                    712
#define PRODUCER_KAI                         713
#define PRODUCER_CHARLOTTE                   714
#define PRODUCER_DEANDRE                     715
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_1       716
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_2       717
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_3       718
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_4       719
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_5       720
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_6       721
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_7       722
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_8       723
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_9       724
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_10      725
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_11      726
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_12      727
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_13      728
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_14      729
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_15      730
#define PRODUCER_GRUNT_MAGMA_HIDEOUT_16      731
#define PRODUCER_TABITHA_MAGMA_HIDEOUT       732
#define PRODUCER_DARCY                       733
#define PRODUCER_MAXIE_MOSSDEEP              734
#define PRODUCER_PETE                        735
#define PRODUCER_ISABELLE                    736
#define PRODUCER_ANDRES_1                    737
#define PRODUCER_JOSUE                       738
#define PRODUCER_CAMRON                      739
#define PRODUCER_CORY_1                      740
#define PRODUCER_CAROLINA                    741
#define PRODUCER_ELIJAH                      742
#define PRODUCER_CELIA                       743
#define PRODUCER_BRYAN                       744
#define PRODUCER_BRANDEN                     745
#define PRODUCER_BRYANT                      746
#define PRODUCER_SHAYLA                      747
#define PRODUCER_KYRA                        748
#define PRODUCER_JAIDEN                      749
#define PRODUCER_ALIX                        750
#define PRODUCER_HELENE                      751
#define PRODUCER_MARLENE                     752
#define PRODUCER_DEVAN                       753
#define PRODUCER_JOHNSON                     754
#define PRODUCER_MELINA                      755
#define PRODUCER_BRANDI                      756
#define PRODUCER_AISHA                       757
#define PRODUCER_MAKAYLA                     758
#define PRODUCER_FABIAN                      759
#define PRODUCER_DAYTON                      760
#define PRODUCER_RACHEL                      761
#define PRODUCER_LEONEL                      762
#define PRODUCER_CALLIE                      763
#define PRODUCER_CALE                        764
#define PRODUCER_MYLES                       765
#define PRODUCER_PAT                         766
#define PRODUCER_CRISTIN_1                   767
#define PRODUCER_MAY_RUSTBORO_TREECKO        768
#define PRODUCER_MAY_RUSTBORO_TORCHIC        769
#define PRODUCER_ROXANNE_2                   770
#define PRODUCER_ROXANNE_3                   771
#define PRODUCER_ROXANNE_4                   772
#define PRODUCER_ROXANNE_5                   773
#define PRODUCER_BRAWLY_2                    774
#define PRODUCER_BRAWLY_3                    775
#define PRODUCER_BRAWLY_4                    776
#define PRODUCER_BRAWLY_5                    777
#define PRODUCER_WATTSON_2                   778
#define PRODUCER_WATTSON_3                   779
#define PRODUCER_WATTSON_4                   780
#define PRODUCER_WATTSON_5                   781
#define PRODUCER_FLANNERY_2                  782
#define PRODUCER_FLANNERY_3                  783
#define PRODUCER_FLANNERY_4                  784
#define PRODUCER_FLANNERY_5                  785
#define PRODUCER_NORMAN_2                    786
#define PRODUCER_NORMAN_3                    787
#define PRODUCER_NORMAN_4                    788
#define PRODUCER_NORMAN_5                    789
#define PRODUCER_WINONA_2                    790
#define PRODUCER_WINONA_3                    791
#define PRODUCER_WINONA_4                    792
#define PRODUCER_WINONA_5                    793
#define PRODUCER_TATE_AND_LIZA_2             794
#define PRODUCER_TATE_AND_LIZA_3             795
#define PRODUCER_TATE_AND_LIZA_4             796
#define PRODUCER_TATE_AND_LIZA_5             797
#define PRODUCER_JUAN_2                      798
#define PRODUCER_JUAN_3                      799
#define PRODUCER_JUAN_4                      800
#define PRODUCER_JUAN_5                      801
#define PRODUCER_ANGELO                      802
#define PRODUCER_DARIUS                      803
#define PRODUCER_STEVEN                      804
#define PRODUCER_ANABEL                      805
#define PRODUCER_TUCKER                      806
#define PRODUCER_SPENSER                     807
#define PRODUCER_GRETA                       808
#define PRODUCER_NOLAND                      809
#define PRODUCER_LUCY                        810
#define PRODUCER_BRANDON                     811
#define PRODUCER_ANDRES_2                    812
#define PRODUCER_ANDRES_3                    813
#define PRODUCER_ANDRES_4                    814
#define PRODUCER_ANDRES_5                    815
#define PRODUCER_CORY_2                      816
#define PRODUCER_CORY_3                      817
#define PRODUCER_CORY_4                      818
#define PRODUCER_CORY_5                      819
#define PRODUCER_PABLO_2                     820
#define PRODUCER_PABLO_3                     821
#define PRODUCER_PABLO_4                     822
#define PRODUCER_PABLO_5                     823
#define PRODUCER_KOJI_2                      824
#define PRODUCER_KOJI_3                      825
#define PRODUCER_KOJI_4                      826
#define PRODUCER_KOJI_5                      827
#define PRODUCER_CRISTIN_2                   828
#define PRODUCER_CRISTIN_3                   829
#define PRODUCER_CRISTIN_4                   830
#define PRODUCER_CRISTIN_5                   831
#define PRODUCER_FERNANDO_2                  832
#define PRODUCER_FERNANDO_3                  833
#define PRODUCER_FERNANDO_4                  834
#define PRODUCER_FERNANDO_5                  835
#define PRODUCER_SAWYER_2                    836
#define PRODUCER_SAWYER_3                    837
#define PRODUCER_SAWYER_4                    838
#define PRODUCER_SAWYER_5                    839
#define PRODUCER_GABRIELLE_2                 840
#define PRODUCER_GABRIELLE_3                 841
#define PRODUCER_GABRIELLE_4                 842
#define PRODUCER_GABRIELLE_5                 843
#define PRODUCER_THALIA_2                    844
#define PRODUCER_THALIA_3                    845
#define PRODUCER_THALIA_4                    846
#define PRODUCER_THALIA_5                    847
#define PRODUCER_MARIELA                     848
#define PRODUCER_ALVARO                      849
#define PRODUCER_EVERETT                     850
#define PRODUCER_RED                         851
#define PRODUCER_LEAF                        852
#define PRODUCER_BRENDAN_PLACEHOLDER         853
#define PRODUCER_MAY_PLACEHOLDER             854

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_PRODUCERS_COUNT can be increased but will take up additional saveblock space

#define PRODUCERS_COUNT                      855
#define MAX_PRODUCERS_COUNT                  864

#endif  // GUARD_CONSTANTS_OPPONENTS_H
