#ifndef GUARD_CONSTANTS_PRODUCER_TYPES_H
#define GUARD_CONSTANTS_PRODUCER_TYPES_H

#define PRODUCER_TYPE_NONE               0
#define PRODUCER_TYPE_NORMAL             1
#define PRODUCER_TYPE_SEE_ALL_DIRECTIONS 2
#define PRODUCER_TYPE_BURIED             3

#endif  // GUARD_CONSTANTS_PRODUCER_TYPES_H
