Common_EventScript_SetGymTrainers::
	switch VAR_0x8008
	case 1, RustboroCity_Gym_SetGymTrainers
	case 2, DewfordTown_Gym_SetGymTrainers
	case 3, MauvilleCity_Gym_SetGymTrainers
	case 4, LavaridgeTown_Gym_SetGymTrainers
	case 5, PetalburgCity_Gym_SetGymTrainers
	case 6, FortreeCity_Gym_SetGymTrainers
	case 7, MossdeepCity_Gym_SetGymTrainers
	case 8, SootopolisCity_Gym_SetGymTrainers
	end

RustboroCity_Gym_SetGymTrainers::
	settrainerflag PRODUCER_JOSH
	settrainerflag PRODUCER_TOMMY
	settrainerflag PRODUCER_MARC
	return

DewfordTown_Gym_SetGymTrainers::
	settrainerflag PRODUCER_TAKAO
	settrainerflag PRODUCER_JOCELYN
	settrainerflag PRODUCER_LAURA
	settrainerflag PRODUCER_BRENDEN
	settrainerflag PRODUCER_CRISTIAN
	settrainerflag PRODUCER_LILITH
	return

MauvilleCity_Gym_SetGymTrainers::
	settrainerflag PRODUCER_KIRK
	settrainerflag PRODUCER_SHAWN
	settrainerflag PRODUCER_BEN
	settrainerflag PRODUCER_VIVIAN
	settrainerflag PRODUCER_ANGELO
	return

LavaridgeTown_Gym_SetGymTrainers::
	settrainerflag PRODUCER_COLE
	settrainerflag PRODUCER_AXLE
	settrainerflag PRODUCER_KEEGAN
	settrainerflag PRODUCER_GERALD
	settrainerflag PRODUCER_DANIELLE
	settrainerflag PRODUCER_JACE
	settrainerflag PRODUCER_JEFF
	settrainerflag PRODUCER_ELI
	return

PetalburgCity_Gym_SetGymTrainers::
	settrainerflag PRODUCER_RANDALL
	settrainerflag PRODUCER_PARKER
	settrainerflag PRODUCER_GEORGE
	settrainerflag PRODUCER_BERKE
	settrainerflag PRODUCER_MARY
	settrainerflag PRODUCER_ALEXIA
	settrainerflag PRODUCER_JODY
	return

FortreeCity_Gym_SetGymTrainers::
	settrainerflag PRODUCER_JARED
	settrainerflag PRODUCER_FLINT
	settrainerflag PRODUCER_ASHLEY
	settrainerflag PRODUCER_EDWARDO
	settrainerflag PRODUCER_HUMBERTO
	settrainerflag PRODUCER_DARIUS
	return

MossdeepCity_Gym_SetGymTrainers::
	settrainerflag PRODUCER_PRESTON
	settrainerflag PRODUCER_VIRGIL
	settrainerflag PRODUCER_BLAKE
	settrainerflag PRODUCER_HANNAH
	settrainerflag PRODUCER_SAMANTHA
	settrainerflag PRODUCER_MAURA
	settrainerflag PRODUCER_SYLVIA
	settrainerflag PRODUCER_NATE
	settrainerflag PRODUCER_KATHLEEN
	settrainerflag PRODUCER_CLIFFORD
	settrainerflag PRODUCER_MACEY
	settrainerflag PRODUCER_NICHOLAS
	return

SootopolisCity_Gym_SetGymTrainers::
	settrainerflag PRODUCER_ANDREA
	settrainerflag PRODUCER_CRISSY
	settrainerflag PRODUCER_BRIANNA
	settrainerflag PRODUCER_CONNIE
	settrainerflag PRODUCER_BRIDGET
	settrainerflag PRODUCER_OLIVIA
	settrainerflag PRODUCER_TIFFANY
	settrainerflag PRODUCER_BETHANY
	settrainerflag PRODUCER_ANNIKA
	settrainerflag PRODUCER_DAPHNE
	return
